"""add new user role

Revision ID: 88b5c231c58f
Revises: 847037f27aee
Create Date: 2025-11-22 17:24:51.595147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88b5c231c58f'
down_revision: Union[str, Sequence[str], None] = '847037f27aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('name', sa.String(length=40), nullable=True))
    op.add_column('user_data', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user_data', sa.Column('phone', sa.String(length=30), nullable=True))
    op.drop_constraint(op.f('uq_user_data_user_id'), 'user_data', type_='unique')
    op.drop_column('user_data', 'created_at')
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'client', 'realtor', name='user_role_enum'), server_default='client', nullable=False))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    op.add_column('user_data', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_data_user_id'), 'user_data', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_data', 'phone')
    op.drop_column('user_data', 'birth_date')
    op.drop_column('user_data', 'name')
    # ### end Alembic commands ###
